version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.2.0
    environment:
      CIRCLE_COMMIT_MESSAGE: << pipeline.trigger_parameters.github_app.commit_message >>
    steps:
      - checkout
      - run: echo $CIRCLE_COMMIT_MESSAGE
      - run: npm ci
      - run: mkdir ./.test-results
      - run:
          name: Run tests
          command: npm run test:ci
      - store_test_results:
          path: ./.test-results
      - persist_to_workspace:
          root: .
          paths:
            - src
            - node_modules
            - package.json
            - package-lock.json
            - README.md
            - LICENSE
            - tsconfig.json
            - tsconfig.prod.json
  build:
    docker:
      - image: cimg/node:20.2.0
    steps:
      - attach_workspace:
          at: .
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - package.json
            - README.md
            - LICENSE
  publish:
    docker:
      - image: cimg/node:20.2.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
            npm publish

workflows:
  workflow:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: main
      - publish:
          requires:
            - build
