version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.2.0
    steps:
      - checkout
      - run: npm ci
      - run: mkdir ./.test-results
      - run:
          name: Run tests
          command: npm run test:ci
      - store_test_results:
          path: ./.test-results
  build:
    docker:
      - image: cimg/node:20.2.0
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - package.json
            - package-lock.json
  publish:
    docker:
      - image: cimg/node:20.2.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
            npm publish

workflows:
  workflow:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: main
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
