version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.2.0
    steps:
      - checkout
      - run: npm ci
      - run: mkdir ~/.test-results
      - run:
          name: Run tests
          command: npm run test:ci
      - store_test_results:
          path: ~/.test-results

workflows:
  test-workflow:
    jobs:
      - test
