name: 'CI/CD Pipeline'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies 💿
        run: npm ci
      - name: Run tests 🧪
        run: npm run test
  build:
    if: github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies 💿
        run: npm ci
      - name: Build 🏗
        run: npm run build
  bump-version:
    permissions:
      contents: write
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: phips28/gh-action-bump-version@master
        name: Automated Version Bump 🚀
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: 'MINOR'
          major-wording: 'MAJOR'
  publish:
    if: github.event_name == 'push'
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to NPM 📦
        run: npm run publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}