name: 'CI/CD Pipeline'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies 💿
        run: npm ci
      - name: Run tests 🧪
        run: npm run test
  check-version-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: check
        name: Check for version change 📝
        uses: EndBug/add-and-commit@v7
      - name: Get the output
        run: echo "The output was ${{ steps.check.outputs.changed }}"
      - name: Fail if no version change
        run: |
          if [ "${{ steps.check.outputs.changed }}" = "false" ]; then
            echo "No version change detected, failing..."
            exit 1
          fi
  build:
    if: github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies 💿
        run: npm ci
      - name: Build 🏗
        run: npm run build
  publish:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to NPM 📦
        run: npm run publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}