name: "PR pipeline"

on:
  pull_request:
    branches:
      - main

jobs:
  bump-npm-version:
    outputs:
      version-changed: ${{ steps.check.outputs.changed }}
      branch: ${{ steps.extract_branch_name.outputs.branch }}
      dependabot: ${{ steps.check_dependabot.outputs.dependabot }}
    permissions:
      contents: write
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Extract branch name 🌳
        id: extract_branch_name
        run: echo "branch=$(echo ${{ github.event.pull_request.head.ref }})" >> $GITHUB_OUTPUT
      - name: Check if PR was triggered by dependabot 🤖
        id: check_dependabot
        run: |
          if [[ "${{ steps.extract_branch_name.outputs.branch }}" == "dependabot"* ]]; then
            echo "PR is from dependabot"
            echo dependabot=true >> $GITHUB_OUTPUT
          else
            echo "PR is not from dependabot"
            echo dependabot=false >> $GITHUB_OUTPUT
          fi
      - id: check
        name: Check for version change 📝
        uses: EndBug/version-check@v2
      - if: steps.check.outputs.changed == 'false'
        id: bump
        name: Version bump 👊
        run: |
          export BUMP_TYPE=$(git log -1 --pretty=%B | grep -Eio '\[(major|minor|patch)\]$' |  sed 's/[][]//g')
          export BUMP_TYPE="${BUMP_TYPE:-patch}"
          echo version=`npm version $BUMP_TYPE --no-git-tag-version` >> $GITHUB_OUTPUT
          echo bump_type=$BUMP_TYPE >> $GITHUB_OUTPUT
      - if: steps.check.outputs.changed == 'false'
        name: Commit and push 📤
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: bumps version to ${{steps.bump.outputs.version}}"
          commit_options: "--no-verify --signoff"
  test:
    if: ${{ needs.bump-npm-version.outputs.proceed == 'true'  }}
    needs: bump-npm-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies 💿
        run: npm ci
      - name: Run tests 🧪
        run: npm run test
  comment-pr:
    if: ${{ needs.bump-npm-version.outputs.dependabot == 'true' && needs.bump-npm-version.outputs.proceed == 'false' }}
    needs: [ bump-npm-version ]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Comment on PR 💬
        uses: mshick/add-pr-comment@v2
        with:
          message: "@dependabot recreate"
          repo-token: ${{ secrets.PAT }}
  enable-auto-merge:
    if: ${{ needs.bump-npm-version.outputs.version-changed == 'true' }}
    permissions:
      contents: write
    needs: bump-npm-version
    runs-on: ubuntu-latest
    outputs:
      dependabot: ${{ steps.check_dependabot.outputs.dependabot }}
      up-to-date: ${{ steps.check-up-to-date.outputs.ok }}
    steps:
      - if: ${{ needs.bump-npm-version.outputs.dependabot == 'true' }}
        name: Enable auto-merge 🍾
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
